services:
  - type: web
    name: rag-knowledge-backend
    runtime: python
    region: oregon
    plan: starter
    rootDir: backend
    branch: main

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"

      - key: GROQ_API_KEY
        sync: false

      - key: FRONTEND_URLS
        value: "https://your-frontend.onrender.com"

    autoDeploy: true

  - type: static
    name: rag-knowledge-frontend
    rootDir: frontend
    branch: main
    buildCommand: npm install && npm run build
    publishPath: dist

    envVars:
      - key: VITE_API_URL
        value: "https://your-backend.onrender.com"

    autoDeploy: true